version: '2'

services:
    dayz:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 2302:2302/udp
            - 2303:2303/udp
            - 2304:2304/udp
            - 2305:2305/udp
            - 8766:8766/udp
        volumes:
            - ./profile_data:/data
            - ./server_files:/server
            - ./serverDZ.cfg:/config.cfg:ro
            - ./.steamcmd:/root/.steam
        environment:
            CONFIG_FILE: /config.cfg
            PROFILE_DIR: /data

            # Stable: 223350
            # Experimental: 1042420
            STEAM_APP_ID: 1042420
