version: '2'

services:
    dayz:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 2302:2302/udp
            - 2303:2303/udp
            - 2304:2304/udp
            - 2305:2305/udp
            - 27015:27015/udp
        volumes:
            # Directory used for "profiles"
            - ./profile_data:/data
            # Directory used for server/mission files etc.
            - ./server_files:/server
            # Server config. This is mounted as "read-only" in the container.
            - ./serverDZ.cfg:/config.cfg:ro

            # Persist SteamCMD updates, so it doesn't need to re-download the update every time...
            - ./.steamcmd:/root/.steam
        environment:
            CONFIG_FILE: /config.cfg
            PROFILE_DIR: /data

            # Stable: 223350
            # Experimental: 1042420
            STEAM_APP_ID: 1042420